import { NextApiResponse, NextApiRequest } from "next";

export const albuns = [
    {
        id: '1',
        name: 'Interestelar',
        img: '/assets/albuns-img/interestelar.jpg',
        beatsIds: ['124', '135', '141', '123', '108', '122', '138',  '128', '137', '139', '112', '140', '106', 
        '107', '143', '134', '112', '131', '129',
        ],
        dataLnc: '2024/06/04',
        beats: [
          { id: '124', name: 'Generation', album_img: '/assets/img-beats/generation.jpg', 
  audio: '/assets/beats/generation(158).mp3', genres: ['spacial', 'supertrap', 'motivational'],
  dataLnc: '2024/04/11',
},
{ id: '135', name: 'Stargaze', album_img: '/assets/img-beats/stargaze.jpg', 
  audio: '/assets/beats/stargaze(150).mp3', genres: ['spacial', 'inspirational', 'ambient'],
  dataLnc: '2024/05/01',
},
{ id: '141', name: 'Ancient', album_img: '/assets/img-beats/ancient.jpg', 
  audio: '/assets/beats/ancient(150).mp3', genres: ['ambient', 'spacial', 'pluggnb', 'chill'],
  dataLnc: '2024/05/06',
},
{ id: '123', name: 'Ufo', album_img: '/assets/img-beats/ufo.png', 
  audio: '/assets/beats/ufo(158).mp3', genres: ['spacial', 'supertrap', 'motivational'],
  dataLnc: '2024/04/10',
},
{ id: '108', name: 'Flyest', album_img: '/assets/img-beats/flyest.jpg', 
  audio: '/assets/beats/flyest(138).mp3', genres: ['spacial', 'ambient', 'chill', 'motivational'],
  dataLnc: '2024/03/02',
},
{ id: '122', name: 'Comet', album_img: '/assets/img-beats/comet.jpg', 
  audio: '/assets/beats/comet(143).mp3', genres: ['spacial', 'supertrap', 'motivational'],
  dataLnc: '2024/04/09',
}, 
{ id: '138', name: 'Interestelar', album_img: '/assets/img-beats/interestelarbeat.jpg', 
  audio: '/assets/beats/interestelarV1(147bpm).mp3', genres: ['ambient', 'spacial', 'emotional'],
  dataLnc: '2024/05/03',
},
{ id: '128', name: 'Moon', album_img: '/assets/img-beats/moon.jpg', 
  audio: '/assets/beats/moon(149).mp3', genres: ['ambient', 'emotional', 'spacial'],
  dataLnc: '2024/04/25',
},
{ id: '137', name: 'Sine', album_img: '/assets/img-beats/sine.jpg', 
  audio: '/assets/beats/sine(141).mp3', genres: ['ambient', 'spacial', 'pluggnb', 'chill'],
  dataLnc: '2024/05/02',
},
{ id: '139', name: 'Deep', album_img: '/assets/img-beats/deeponit.jpg', 
  audio: '/assets/beats/deep on it.mp3', genres: ['ambient', 'spacial', 'pluggnb', 'emotional'],
  dataLnc: '2024/05/04',
},
{ id: '140', name: 'Alchemy', album_img: '/assets/img-beats/alchemy.jpg', 
  audio: '/assets/beats/alchemy(136).mp3', genres: ['ambient', 'spacial', 'chill'],
  dataLnc: '2024/05/05',
},
{ id: '106', name: 'Nasa', album_img: '/assets/img-beats/nasa.jpg', 
  audio: '/assets/beats/nasa.mp3', genres: ['spacial', 'ambient', 'chill'],
  dataLnc: '2024/02/27',
},
{ id: '107', name: 'Pluto', album_img: '/assets/img-beats/pluto.jpg', 
  audio: '/assets/beats/pluto(154).mp3', genres: ['spacial', 'ambient', 'dark'],
  dataLnc: '2024/03/01',
},
{ id: '143', name: 'Void', album_img: '/assets/img-beats/void.jpg', 
  audio: '/assets/beats/deicide - void(150bpm).mp3', genres: ['spacial', 'inspirational', 'agressive'],
  dataLnc: '2024/05/07',
},
{ id: '134', name: 'Opera', album_img: '/assets/img-beats/opera.jpg', 
  audio: '/assets/beats/spacyviolin(146).mp3', genres: ['ambient', 'inspirational', 'regalia', 'spacial'],
  dataLnc: '2024/04/30',
},
{ id: '112', name: 'Spaceship', album_img: '/assets/img-beats/spaceship.jpg', 
  audio: '/assets/beats/spaceship(147)Fminor.mp3', genres: ['ambient', 'spacial', 'rage', 'supertrap', 'motivational'],
  dataLnc: '2024/03/21',
},
{ id: '131', name: 'Scape', album_img: '/assets/img-beats/scape.png', 
  audio: '/assets/beats/scape(156).mp3', genres: ['agressive', 'spacial'],
  dataLnc: '2024/04/28',
},
{ id: '129', name: 'Plasma', album_img: '/assets/img-beats/plasma.jpg', 
  audio: '/assets/beats/plasma(152).mp3', genres: ['ambient','agressive', 'spacial'],
  dataLnc: '2024/04/26',
},
        ],
    },
]

export default function handler(req: NextApiRequest, res: NextApiResponse) {
    if (req.method === 'GET') {
      res.status(200).json(albuns);
    } else {
      res.status(405).end();
    }
  }