import type { NextApiRequest, NextApiResponse } from 'next'


export const beats = [
  { id: '0', name: 'Chill/Codein', album_img: '/assets/img-beats/codeinchill.png', 
    audio: '/assets/beats/codeinchill.mp3', genres: ['plugg', 'pluggnb'],
    dataLnc: '2023/01/22',
  },
  { id: '1', name: 'Purple', album_img: '/assets/img-beats/purple.png', 
    audio: '/assets/beats/(pluggnb)purple_.mp3', genres: ['plugg', 'pluggnb'],
    dataLnc: '2023/01/24',
  },
  { id: '2', name: 'Bounce', album_img: '/assets/img-beats/bounce.png', 
    audio: '/assets/beats/(westcoast)bounce.mp3', genres: ['westcoast'],
    dataLnc: '2023/02/27',
  },
  { id: '3', name: 'Ride', album_img: '/assets/img-beats/ride.png', 
    audio: '/assets/beats/(hide)ride.mp3', genres: ['hard', 'gangsta'],
    dataLnc: '2023/03/15',
  },
  { id: '4', name: 'Slay', album_img: '/assets/img-beats/slay.png', 
    audio: '/assets/beats/slay.mp3', genres: ['dark', 'hard'],
    dataLnc: '2023/03/19',
  },
  { id: '5', name: 'Bape', album_img: '/assets/img-beats/bape.png', 
    audio: '/assets/beats/bape.mp3', genres: ['plugg', 'pluggnb'],
    dataLnc: '2023/04/03',
  },
  { id: '6', name: 'Angels', album_img: '/assets/img-beats/angels.png', 
    audio: '/assets/beats/angels.mp3', genres: ['ambient', 'dark', 'melodic', 'sad'],
    dataLnc: '2023/06/28',
  },
  { id: '7', name: 'Glock19', album_img: '/assets/img-beats/glock19.png', 
    audio: '/assets/beats/glock19.mp3', genres: ['dark', 'hard', 'darkplugg'],
    dataLnc: '2023/07/20',
  },
  { id: '8', name: 'Evil', album_img: '/assets/img-beats/evil.png', 
    audio: '/assets/beats/evil.mp3', genres: ['dark', 'hard', 'ambient'],
    dataLnc: '2023/07/22',
  },
  { id: '9', name: 'Xanax Dreams', album_img: '/assets/img-beats/xanaxdreams.jpg', 
    audio: '/assets/beats/XanaxDreams.mp3', genres: ['ambient', 'chill'],
    dataLnc: '2023/07/26',
  },
  { id: '10', name: 'Cristals', album_img: '/assets/img-beats/cristalsbg.jpg', 
    audio: '/assets/beats/cristals.mp3', genres: ['ambient', 'chill'],
    dataLnc: '2023/07/30',
  },
  { id: '11', name: 'Vetements', album_img: '/assets/img-beats/vetements.jpg', 
    audio: '/assets/beats/vetements.mp3', genres: ['ambient', 'chill', 'dark'],
    dataLnc: '2023/08/02',
  },
  { id: '12', name: 'Guap', album_img: '/assets/img-beats/guap.png', 
    audio: '/assets/beats/guap.mp3', genres: ['westcoast', 'gangsta', 'dark'],
    dataLnc: '2023/08/02',
  },
  { id: '13', name: 'Everyday', album_img: '/assets/img-beats/everyday.png', 
    audio: '/assets/beats/everyday.mp3', genres: ['rage', 'agressive'],
    dataLnc: '2023/08/08',
  },
  { id: '14', name: 'Violence', album_img: '/assets/img-beats/violence.png', 
    audio: '/assets/beats/violence.mp3', genres: ['dark', 'agressive', 'hard'],
    dataLnc: '2023/08/09',
  },
  { id: '15', name: 'Better days', album_img: '/assets/img-beats/betterdays.png', 
    audio: '/assets/beats/betterdays.mp3', genres: ['westcoast', 'chill', 'gangsta'],
    dataLnc: '2023/08/09',
  },
  { id: '16', name: 'Clouds', album_img: '/assets/img-beats/clouds.png', 
    audio: '/assets/beats/clouds.mp3', genres: ['chill', 'lofi'],
    dataLnc: '2023/08/18',
  },
  { id: '17', name: 'Sea', album_img: '/assets/img-beats/sea.png', 
    audio: '/assets/beats/sea.mp3', genres: ['chill', 'lofi'],
    dataLnc: '2023/08/18',
  },
  { id: '18', name: 'Blank', album_img: '/assets/img-beats/blank.jpg', 
    audio: '/assets/beats/blank.mp3', genres: ['chill', 'dark', 'gangsta'],
    dataLnc: '2023/08/20',
  },
  { id: '19', name: 'Winter', album_img: '/assets/img-beats/winter.png', 
    audio: '/assets/beats/winter.mp3', genres: ['chill', 'altrock', 'vibe'],
    dataLnc: '2023/08/29',
  },
  { id: '20', name: 'Citric', album_img: '/assets/img-beats/citric.png', 
    audio: '/assets/beats/citric.mp3', genres: ['ambient', 'dark', 'chill', 'vibe'],
    dataLnc: '2023/08/31',
  },
  { id: '21', name: 'Slidin', album_img: '/assets/img-beats/slidin.png', 
    audio: '/assets/beats/slidin.mp3', genres: ['westcoast', 'gangsta'],
    dataLnc: '2023/09/06',
  },
  { id: '22', name: 'Poison', album_img: '/assets/img-beats/poison.png', 
    audio: '/assets/beats/poison.mp3', genres: ['dark', 'plugg', 'darkplugg'],
    dataLnc: '2023/09/09',
  },
  { id: '23', name: 'Diamonds', album_img: '/assets/img-beats/diamonds.png', 
    audio: '/assets/beats/diamonds.mp3', genres: ['gangsta', 'hard'],
    dataLnc: '2023/09/09',
  },
  { id: '24', name: 'Aurea', album_img: '/assets/img-beats/aurea.png', 
    audio: '/assets/beats/aurea.mp3', genres: ['asianrock', 'pluggnb', 'chill'],
    dataLnc: '2023/09/18',
  },
  { id: '25', name: '4ever Alive', album_img: '/assets/img-beats/4everalive.png', 
    audio: '/assets/beats/4everalive.mp3', genres: ['chill', 'ambient'],
    dataLnc: '2023/09/19',
  },
  { id: '26', name: 'Hysteric', album_img: '/assets/img-beats/hysteric.png', 
    audio: '/assets/beats/hysteric.mp3', genres: ['plugg', 'pluggnb'],
    dataLnc: '2023/09/20',
  },
  { id: '27', name: 'Space', album_img: '/assets/img-beats/space.png', 
    audio: '/assets/beats/space.mp3', genres: ['rage', 'ambient'],
    dataLnc: '2023/09/21',
  },
  { id: '28', name: 'Fashion', album_img: '/assets/img-beats/Fashion.png', 
    audio: '/assets/beats/fashion.mp3', genres: ['rage', 'opium'],
    dataLnc: '2023/09/21',
  },
  { id: '29', name: 'Perk', album_img: '/assets/img-beats/perk.png', 
    audio: '/assets/beats/perk.mp3', genres: ['rage'],
    dataLnc: '2023/09/22',
  },
  { id: '30', name: 'Midnight', album_img: '/assets/img-beats/midnight.png', 
    audio: '/assets/beats/midnight.mp3', genres: ['westcoast'],
    dataLnc: '2023/09/26',
  },
  { id: '31', name: 'War', album_img: '/assets/img-beats/war.png', 
    audio: '/assets/beats/war.mp3', genres: ['gangsta'],
    dataLnc: '2023/09/27',
  },
  { id: '32', name: 'Bandolero', album_img: '/assets/img-beats/bandolero.png', 
    audio: '/assets/beats/bandolero.mp3', genres: ['detroit', 'gangsta'],
    dataLnc: '2023/10/01',
  },
  { id: '33', name: 'Prada walkin', album_img: '/assets/img-beats/pradawalkin.png', 
    audio: '/assets/beats/pradawalkin.mp3', genres: ['detroit', 'gangsta'],
    dataLnc: '2023/10/01',
  },
  { id: '34', name: 'Switch', album_img: '/assets/img-beats/switch.png', 
    audio: '/assets/beats/switch.mp3', genres: ['ambient', 'dark', 'spacial'],
    dataLnc: '2023/10/02',
  },{ id: '35', name: 'Emotions', album_img: '/assets/img-beats/emotions.png', 
  audio: '/assets/beats/emotions.mp3', genres: ['vibe', 'chill', 'emotional'],
  dataLnc: '2023/10/04',
},
{ id: '36', name: 'Horror', album_img: '/assets/img-beats/horror.png', 
  audio: '/assets/beats/horror.mp3', genres: ['dark', 'darkplugg', 'plugg'],
  dataLnc: '2023/10/05',
},
{ id: '37', name: 'Sky High', album_img: '/assets/img-beats/skyhigh.png', 
  audio: '/assets/beats/skyhigh.mp3', genres: ['plugg', 'pluggnb'],
  dataLnc: '2023/10/06',
},
{ id: '38', name: 'BootUp', album_img: '/assets/img-beats/bootup.png', 
  audio: '/assets/beats/bootup.mp3', genres: ['rage', 'agressive'],
  dataLnc: '2023/10/07',
},
{ id: '39', name: 'Servin', album_img: '/assets/img-beats/servin.png', 
  audio: '/assets/beats/servin.mp3', genres: ['glo', 'agressive', 'gangsta'],
  dataLnc: '2023/10/08',
},
{ id: '40', name: 'My luv', album_img: '/assets/img-beats/myluv.png', 
  audio: '/assets/beats/myluv.mp3', genres: ['pluggnb', 'plugg'],
  dataLnc: '2023/10/09',
},
{ id: '41', name: 'Beamer', album_img: '/assets/img-beats/beamer.png', 
  audio: '/assets/beats/beamer.mp3', genres: ['westcoast', 'gangsta'],
  dataLnc: '2023/10/11',
},
{ id: '42', name: 'Rain', album_img: '/assets/img-beats/rain.png', 
  audio: '/assets/beats/rain.mp3', genres: ['ambient', 'emotional'],
  dataLnc: '2023/10/15',
},
{ id: '43', name: 'Lsd', album_img: '/assets/img-beats/lsd.png', 
    audio: '/assets/beats/lsd.mp3', genres: ['ambient', 'hyperpop'],
    dataLnc: '2023/10/16',
  },
  { id: '44', name: 'Hell nah', album_img: '/assets/img-beats/hellnah.png', 
    audio: '/assets/beats/hellnah.mp3', genres: ['rage', 'agressive'],
    dataLnc: '2023/10/17',
  },
  { id: '45', name: 'Your calls', album_img: '/assets/img-beats/yourcalls.png', 
    audio: '/assets/beats/yourcalls.mp3', genres: ['detroit', 'gangsta', 'chill'],
    dataLnc: '2023/10/18',
  },
  { id: '46', name: 'Motivation', album_img: '/assets/img-beats/motivation.png', 
    audio: '/assets/beats/motivation.mp3', genres: ['detroit', 'gangsta', 'chill'],
    dataLnc: '2023/10/19',
  },
  { id: '47', name: 'Ps2', album_img: '/assets/img-beats/ps2.png', 
    audio: '/assets/beats/ps2.mp3', genres: ['chill'],
    dataLnc: '2023/10/20',
  },
  { id: '48', name: 'Beethoven', album_img: '/assets/img-beats/bethoven.png', 
    audio: '/assets/beats/bethoven.mp3', genres: ['detroit', 'flint', 'gangsta'],
    dataLnc: '2023/10/21',
  },
  { id: '49', name: 'Heaven sent', album_img: '/assets/img-beats/heavensent.png', 
    audio: '/assets/beats/heavensent.mp3', genres: ['regalia'],
    dataLnc: '2023/10/22',
  },
  { id: '50', name: 'Universal', album_img: '/assets/img-beats/universal.jpg', 
    audio: '/assets/beats/universal.mp3', genres: ['regalia', 'motivational'],
    dataLnc: '2023/10/23',
  },
  { id: '51', name: 'Flawless', album_img: '/assets/img-beats/flawless.png', 
    audio: '/assets/beats/flawless.mp3', genres: ['glo', 'regalia', 'motivational'],
    dataLnc: '2023/10/24',
  },
  { id: '52', name: 'Crumble', album_img: '/assets/img-beats/crumble.png', 
    audio: '/assets/beats/crumble.mp3', genres: ['regalia', 'motivational'],
    dataLnc: '2023/10/30',
  },
  { id: '53', name: 'Toxic', album_img: '/assets/img-beats/toxic.png', 
    audio: '/assets/beats/toxic.mp3', genres: ['dark', 'rage', 'aggressive'],
    dataLnc: '2023/10/31',
  },
  { id: '54', name: 'Aliens', album_img: '/assets/img-beats/aliens.png', 
    audio: '/assets/beats/aliens.mp3', genres: ['supertrap'],
    dataLnc: '2023/11/01',
  },
  { id: '55', name: 'Vacant', album_img: '/assets/img-beats/vacant.png', 
    audio: '/assets/beats/vacant.mp3', genres: ['altrock', 'vibe'],
    dataLnc: '2023/11/02',
  },
  { id: '56', name: 'Ethereal', album_img: '/assets/img-beats/ethereal.png', 
    audio: '/assets/beats/ethereal.mp3', genres: ['eletronic'],
    dataLnc: '2023/11/03',
  },
  { id: '57', name: 'Gone', album_img: '/assets/img-beats/gone.png', 
    audio: '/assets/beats/gone.mp3', genres: ['dark', 'rage', 'aggressive', 'gangsta'],
    dataLnc: '2023/11/04',
  },
  { id: '58', name: 'Moonrock', album_img: '/assets/img-beats/moonrock.png', 
    audio: '/assets/beats/moonrock.mp3', genres: ['detroit', 'chill', 'gangsta'],
    dataLnc: '2023/11/05',
  },
  { id: '59', name: 'Storm', album_img: '/assets/img-beats/storm.png', 
    audio: '/assets/beats/storm.mp3', genres: ['deep', 'trip', 'emotional'],
    dataLnc: '2023/11/06',
  },
  { id: '60', name: 'Cloudy', album_img: '/assets/img-beats/cloudy.png', 
    audio: '/assets/beats/cloudy.mp3', genres: ['dark', 'experimental'],
    dataLnc: '2023/11/07',
  },
  { id: '61', name: 'Charger', album_img: '/assets/img-beats/charger.png', 
    audio: '/assets/beats/charger.mp3', genres: ['detroit', 'flint', 'gangsta', 'motivational'],
    dataLnc: '2023/11/08',
  },
  { id: '62', name: 'Village', album_img: '/assets/img-beats/village.png', 
    audio: '/assets/beats/village.mp3', genres: ['pluggnb', 'asianrock', 'chill'],
    dataLnc: '2023/11/09',
  },
  { id: '63', name: 'Flex like this', album_img: '/assets/img-beats/flexlikethis.png', 
    audio: '/assets/beats/flexlikethis.mp3', genres: ['vibe', 'hyperpop'],
    dataLnc: '2023/11/10',
  },
  { id: '64', name: 'Wind', album_img: '/assets/img-beats/wind.png', 
  audio: '/assets/beats/wind.mp3', genres: ['plugg', 'pluggnb', 'asianrock'],
  dataLnc: '2023/11/11',
},
{ id: '65', name: 'Lua', album_img: '/assets/img-beats/lua.png', 
  audio: '/assets/beats/lua.mp3', genres: ['pluggnb', 'plugg', 'emotional'],
  dataLnc: '2023/11/12',
},
{ id: '66', name: 'Honey', album_img: '/assets/img-beats/honey.png', 
  audio: '/assets/beats/honey.mp3', genres: ['pluggnb', 'chill'],
  dataLnc: '2023/11/13',
},
{ id: '67', name: 'Mirrors', album_img: '/assets/img-beats/mirrors.png', 
  audio: '/assets/beats/mirrors.mp3', genres: ['ambient', 'deep', 'dark'],
  dataLnc: '2023/11/14',
},
{ id: '68', name: 'Icon', album_img: '/assets/img-beats/icon.png', 
  audio: '/assets/beats/icon.mp3', genres: ['dark', 'opium'],
  dataLnc: '2023/11/15',
},
{ id: '69', name: 'Merciless', album_img: '/assets/img-beats/merciless.png', 
  audio: '/assets/beats/merciless.mp3', genres: ['dark', 'agressive', 'gangsta'],
  dataLnc: '2023/11/16',
},
{ id: '70', name: 'Power', album_img: '/assets/img-beats/power.png', 
  audio: '/assets/beats/power.mp3', genres: ['gangsta'],
  dataLnc: '2023/11/17',
},
{ id: '71', name: 'Sacred', album_img: '/assets/img-beats/sacred.png', 
  audio: '/assets/beats/sacred.mp3', genres: ['dark', 'agressive', 'opium'],
  dataLnc: '2023/11/18',
},
{ id: '72', name: 'Sides', album_img: '/assets/img-beats/sides.png', 
  audio: '/assets/beats/sides.mp3', genres: ['pluggnb', 'asianrock'],
  dataLnc: '2023/11/19',
},
{ id: '73', name: 'Float', album_img: '/assets/img-beats/float.png', 
  audio: '/assets/beats/float.mp3', genres: ['plugg', 'chill', 'pluggnb'],
  dataLnc: '2023/11/20',
},
{ id: '74', name: 'Maybach', album_img: '/assets/img-beats/maybach.png', 
  audio: '/assets/beats/maybach.mp3', genres: ['gangsta', 'dark', 'agressive'],
  dataLnc: '2023/11/21',
},
{ id: '75', name: 'Secrets', album_img: '/assets/img-beats/secrets.png', 
  audio: '/assets/beats/secrets.mp3', genres: ['ambient', 'dark', 'deep'],
  dataLnc: '2023/11/22',
},
{ id: '76', name: 'Cosmic', album_img: '/assets/img-beats/cosmic.png', 
  audio: '/assets/beats/cosmic.mp3', genres: ['ambient', 'chill', 'emotional'],
  dataLnc: '2023/11/23',
},
{ id: '77', name: 'Blow em', album_img: '/assets/img-beats/blowem.png', 
  audio: '/assets/beats/blowem.mp3', genres: ['rage'],
  dataLnc: '2023/11/24',
},
{ id: '78', name: 'Spaced out', album_img: '/assets/img-beats/spacedout.png', 
  audio: '/assets/beats/spacedout.mp3', genres: ['ambient', 'opium', 'spacial'],
  dataLnc: '2023/11/25',
},
{ id: '79', name: 'Attraction', album_img: '/assets/img-beats/attraction.png', 
  audio: '/assets/beats/attraction.mp3', genres: ['ambient', 'deep', 'dark'],
  dataLnc: '2023/11/26',
},
{ id: '80', name: 'Whip', album_img: '/assets/img-beats/whip.png', 
  audio: '/assets/beats/whip.mp3', genres: ['ambient', 'chill'],
  dataLnc: '2023/11/27',
},
{ id: '81', name: 'Plans', album_img: '/assets/img-beats/plans.png', 
  audio: '/assets/beats/plans.mp3', genres: ['motivational'],
  dataLnc: '2023/11/28',
},
{ id: '82', name: 'Ascendent', album_img: '/assets/img-beats/ascendent.png', 
  audio: '/assets/beats/ascendent.mp3', genres: ['regalia', 'motivational'],
  dataLnc: '2023/11/29',
},
{ id: '83', name: 'Goals', album_img: '/assets/img-beats/goals.png', 
  audio: '/assets/beats/goals.mp3', genres: ['regalia', 'motivational', 'dark'],
  dataLnc: '2023/11/30',
},
{ id: '84', name: 'Chinatown', album_img: '/assets/img-beats/chinatown.png', 
  audio: '/assets/beats/chinatown.mp3', genres: ['eletronic', 'dark'],
  dataLnc: '2023/12/01',
},
{ id: '85', name: 'Killer', album_img: '/assets/img-beats/killer.png', 
  audio: '/assets/beats/killer.mp3', genres: ['jerk', 'dark', 'agressive'],
  dataLnc: '2023/12/02',
},
{ id: '86', name: 'Advance', album_img: '/assets/img-beats/advance.png', 
  audio: '/assets/beats/advance.mp3', genres: ['rage', 'supertrap'],
  dataLnc: '2023/12/03',
},
{ id: '87', name: 'Spiral', album_img: '/assets/img-beats/spiral.png', 
  audio: '/assets/beats/spiral.mp3', genres: ['supertrap', 'rage'],
  dataLnc: '2023/12/04',
},
{ id: '88', name: 'Coldest', album_img: '/assets/img-beats/coldest.png', 
  audio: '/assets/beats/coldest.mp3', genres: ['newjazz', 'chill', 'motivational'],
  dataLnc: '2023/12/05',
},
{ id: '89', name: 'Hills', album_img: '/assets/img-beats/hills.png', 
  audio: '/assets/beats/hills.mp3', genres: ['ambient', 'chill', 'deep', 'dark'],
  dataLnc: '2023/12/06',
},
{ id: '90', name: 'Wicked Luv', album_img: '/assets/img-beats/wickedluv.png', 
  audio: '/assets/beats/wickedluv.mp3', genres: ['pluggnb', 'chill', 'emotional'],
  dataLnc: '2023/12/07',
},
{ id: '91', name: 'Illusions', album_img: '/assets/img-beats/illusions.png', 
  audio: '/assets/beats/illusions.mp3', genres: ['pluggnb', 'deep', 'dark', 'emotional'],
  dataLnc: '2023/12/08',
},
{ id: '92', name: 'Sanity', album_img: '/assets/img-beats/sanity.png', 
  audio: '/assets/beats/sanity.mp3', genres: ['supertrap', 'dark', 'motivational', 'spacial'],
  dataLnc: '2023/12/09',
},
{ id: '93', name: 'Dimension', album_img: '/assets/img-beats/dimension.png', 
  audio: '/assets/beats/dimension.mp3', genres: ['supertrap', 'spacial', 'dark'],
  dataLnc: '2023/12/10',
},
{ id: '94', name: 'Danger', album_img: '/assets/img-beats/danger.png', 
  audio: '/assets/beats/danger.mp3', genres: ['supertrap', 'rage', 'agressive', 'dark'],
  dataLnc: '2023/12/11',
},
{ id: '95', name: 'Pouring', album_img: '/assets/img-beats/pouring.png', 
  audio: '/assets/beats/pouring.mp3', genres: ['plugg', 'chill', 'motivational', 'vibe'],
  dataLnc: '2023/12/12',
},
{ id: '96', name: 'When it Rains', album_img: '/assets/img-beats/whenitrains.png', 
  audio: '/assets/beats/whenitrains.mp3', genres: ['ambient', 'chill', 'deep', 'emotional'],
  dataLnc: '2023/12/13',
},
{ id: '97', name: 'Elevated', album_img: '/assets/img-beats/elevate.png', 
  audio: '/assets/beats/elevate.mp3', genres: ['rage', 'supertrap', 'agressive'],
  dataLnc: '2023/12/14',
},
{ id: '98', name: 'Sippin', album_img: '/assets/img-beats/sippin.png', 
  audio: '/assets/beats/spinnin.mp3', genres: ['supertrap', 'dark', 'spacial'],
  dataLnc: '2023/12/15',
},
{ id: '99', name: 'X2C', album_img: '/assets/img-beats/x2c.png', 
  audio: '/assets/beats/x2c.mp3', genres: ['supertrap', 'ambient', 'chill'],
  dataLnc: '2023/12/16',
},
{ id: '100', name: 'AMG GT73', album_img: '/assets/img-beats/amgcedes.png', 
  audio: '/assets/beats/amgcedes.mp3', genres: ['supertrap', 'ambient', 'spacial', 'chill'],
  dataLnc: '2023/12/17',
},
{ id: '101', name: 'Synergy X', album_img: '/assets/img-beats/synergyx.png', 
  audio: '/assets/beats/synergyx.mp3', genres: ['supertrap', 'ambient', 'spacial', 'chill'],
  dataLnc: '2024/02/14',
},
{ id: '102', name: 'Tryptamine', album_img: '/assets/img-beats/tryptamine.png', 
  audio: '/assets/beats/tryptamine(141).mp3', genres: ['eletronic', 'ambient', 'spacial', 'chill'],
  dataLnc: '2024/02/16',
},
{ id: '103', name: 'Muddy days', album_img: '/assets/img-beats/muddydays.jpg', 
  audio: '/assets/beats/muddydays.mp3', genres: ['pluggnb', 'plugg', 'chill'],
  dataLnc: '2024/02/18',
},
{ id: '104', name: 'Swervin', album_img: '/assets/img-beats/swervin.jpg', 
  audio: '/assets/beats/swervin.mp3', genres: ['ambient', 'dark'],
  dataLnc: '2024/02/20',
},
{ id: '105', name: 'Frailty', album_img: '/assets/img-beats/frailty.jpg', 
  audio: '/assets/beats/frailty.mp3', genres: ['pluggnb', 'plugg', 'chill', 'dark'],
  dataLnc: '2024/02/24',
},
{ id: '106', name: 'Nasa', album_img: '/assets/img-beats/nasa.jpg', 
  audio: '/assets/beats/nasa.mp3', genres: ['spacial', 'ambient', 'chill'],
  dataLnc: '2024/02/27',
},
{ id: '107', name: 'Pluto', album_img: '/assets/img-beats/pluto.jpg', 
  audio: '/assets/beats/pluto(154).mp3', genres: ['spacial', 'ambient', 'dark'],
  dataLnc: '2024/03/01',
},
{ id: '108', name: 'Flyest', album_img: '/assets/img-beats/flyest.jpg', 
  audio: '/assets/beats/flyest(138).mp3', genres: ['spacial', 'ambient', 'chill', 'motivational'],
  dataLnc: '2024/03/02',
},
{ id: '109', name: 'Purity', album_img: '/assets/img-beats/purity.jpg', 
  audio: '/assets/beats/purity(142).mp3', genres: ['ambient', 'chill', 'motivational'],
  dataLnc: '2024/03/03',
},
{ id: '110', name: 'Liquid', album_img: '/assets/img-beats/liquid.jpg', 
  audio: '/assets/beats/liquid.mp3', genres: ['ambient', 'chill',  'motivational'],
  dataLnc: '2024/03/15',
},
{ id: '111', name: 'Scored', album_img: '/assets/img-beats/scored.jpg', 
  audio: '/assets/beats/scored(170).mp3', genres: ['ambient', 'spacial', 'rage', 'supertrap', 'motivational'],
  dataLnc: '2024/03/16',
},
{ id: '112', name: 'Spaceship', album_img: '/assets/img-beats/spaceship.jpg', 
  audio: '/assets/beats/spaceship(147)Fminor.mp3', genres: ['ambient', 'spacial', 'rage', 'supertrap', 'motivational'],
  dataLnc: '2024/03/21',
},
{ id: '113', name: 'Cybercity', album_img: '/assets/img-beats/cybercity.jpg', 
  audio: '/assets/beats/cybercity(133).mp3', genres: ['ambient', 'spacial', 'rage', 'supertrap', 'motivational'],
  dataLnc: '2024/03/28',
},
{ id: '114', name: 'Vamply', album_img: '/assets/img-beats/roller.jpg', 
  audio: '/assets/beats/roller(160)Eminor.mp3', genres: ['ambient', 'dark'],
  dataLnc: '2024/03/27',
},
{ id: '115', name: 'Geeker', album_img: '/assets/img-beats/geeker.png', 
  audio: '/assets/beats/geeker(140).mp3', genres: ['ambient', 'dark'],
  dataLnc: '2024/03/26',
},
{ id: '116', name: 'Scammed', album_img: '/assets/img-beats/scammed.jpg', 
  audio: '/assets/beats/scammed(140).mp3', genres: ['ambient', 'dark'],
  dataLnc: '2024/04/03',
},
];

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === 'GET') {
    res.status(200).json(beats);
  } else {
    res.status(405).end();
  }
}