import type { NextApiRequest, NextApiResponse } from 'next'


export const beats = [
  { id: '0', name: 'Codein chill', album_img: '/assets/img-beats/codeinchill.png', 
    audio: '/assets/beats/codeinchill.mp3', genres: ['plugg', 'pluggnb'],
    dataLnc: '2023/01/22',
  },
  { id: '1', name: 'Purple', album_img: '/assets/img-beats/purple.png', 
    audio: '/assets/beats/(pluggnb)purple_.mp3', genres: ['plugg', 'pluggnb'],
    dataLnc: '2023/01/24',
  },
  { id: '2', name: 'Bounce', album_img: '/assets/img-beats/bounce.png', 
    audio: '/assets/beats/(westcoast)bounce.mp3', genre: 'westcoast',
    dataLnc: '2023/02/27',
  },
  { id: '3', name: 'Ride', album_img: '/assets/img-beats/ride.png', 
    audio: '/assets/beats/(hide)ride.mp3', genres: ['hard', 'gangsta'],
    dataLnc: '2023/03/15',
  },
  { id: '4', name: 'Slay', album_img: '/assets/img-beats/slay.png', 
    audio: '/assets/beats/slay.mp3', genres: ['dark', 'hard'],
    dataLnc: '2023/03/19',
  },
  { id: '5', name: 'Bape', album_img: '/assets/img-beats/bape.png', 
    audio: '/assets/beats/bape.mp3', genres: ['plugg', 'pluggnb'],
    dataLnc: '2023/04/03',
  },
  { id: '6', name: 'Angels', album_img: '/assets/img-beats/angels.png', 
    audio: '/assets/beats/angels.mp3', genres: ['ambient', 'dark', 'melodic', 'sad'],
    dataLnc: '2023/06/28',
  },
  { id: '7', name: 'Glock19', album_img: '/assets/img-beats/glock19.png', 
    audio: '/assets/beats/glock19.mp3', genres: ['dark', 'hard', 'darkplugg'],
    dataLnc: '2023/07/20',
  },
  { id: '8', name: 'Evil', album_img: '/assets/img-beats/evil.png', 
    audio: '/assets/beats/evil.mp3', genres: ['dark', 'hard', 'ambient'],
    dataLnc: '2023/07/22',
  },
  { id: '9', name: 'Xanax Dreams', album_img: '/assets/img-beats/xanaxdreams.jpg', 
    audio: '/assets/beats/XanaxDreams.mp3', genres: ['ambient', 'chill'],
    dataLnc: '2023/07/26',
  },
  { id: '10', name: 'Cristals', album_img: '/assets/img-beats/cristalsbg.jpg', 
    audio: '/assets/beats/cristals.mp3', genres: ['ambient', 'chill'],
    dataLnc: '2023/07/30',
  },
  { id: '11', name: 'Vetements', album_img: '/assets/img-beats/vetements.jpg', 
    audio: '/assets/beats/vetements.mp3', genres: ['ambient', 'chill', 'dark'],
    dataLnc: '2023/08/02',
  },
  { id: '12', name: 'Guap', album_img: '/assets/img-beats/guap.png', 
    audio: '/assets/beats/guap.mp3', genres: ['westcoast', 'gangsta', 'dark'],
    dataLnc: '2023/08/02',
  },
  { id: '13', name: 'Everyday', album_img: '/assets/img-beats/everyday.png', 
    audio: '/assets/beats/everyday.mp3', genres: ['rage', 'agressive'],
    dataLnc: '2023/08/08',
  },
  { id: '14', name: 'Violence', album_img: '/assets/img-beats/violence.png', 
    audio: '/assets/beats/violence.mp3', genres: ['dark', 'agressive', 'hard'],
    dataLnc: '2023/08/09',
  },
  { id: '15', name: 'Better days', album_img: '/assets/img-beats/betterdays.png', 
    audio: '/assets/beats/betterdays.mp3', genres: ['westcoast', 'chill', 'gangsta'],
    dataLnc: '2023/08/09',
  },
  { id: '16', name: 'Clouds', album_img: '/assets/img-beats/clouds.png', 
    audio: '/assets/beats/clouds.mp3', genres: ['chill', 'lofi'],
    dataLnc: '2023/08/18',
  },
  { id: '17', name: 'Sea', album_img: '/assets/img-beats/sea.png', 
    audio: '/assets/beats/sea.mp3', genres: ['chill', 'lofi'],
    dataLnc: '2023/08/18',
  },
  { id: '18', name: 'Blank', album_img: '/assets/img-beats/blank.jpg', 
    audio: '/assets/beats/blank.mp3', genres: ['chill', 'dark', 'gangsta'],
    dataLnc: '2023/08/20',
  },
  { id: '19', name: 'Winter', album_img: '/assets/img-beats/winter.png', 
    audio: '/assets/beats/winter.mp3', genres: ['chill', 'altrock'],
    dataLnc: '2023/08/29',
  },
  { id: '20', name: 'Citric', album_img: '/assets/img-beats/citric.png', 
    audio: '/assets/beats/citric.mp3', genres: ['ambient', 'dark', 'chill', 'vibe'],
    dataLnc: '2023/08/31',
  },
  { id: '21', name: 'Slidin', album_img: '/assets/img-beats/slidin.png', 
    audio: '/assets/beats/slidin.mp3', genres: ['westcoast', 'gangsta'],
    dataLnc: '2023/09/06',
  },
  { id: '22', name: 'Poison', album_img: '/assets/img-beats/poison.png', 
    audio: '/assets/beats/poison.mp3', genres: ['dark', 'plugg', 'darkplugg'],
    dataLnc: '2023/09/09',
  },
  { id: '23', name: 'Diamonds', album_img: '/assets/img-beats/diamonds.png', 
    audio: '/assets/beats/diamonds.mp3', genres: ['gangsta', 'hard'],
    dataLnc: '2023/09/09',
  },
  { id: '24', name: 'Aurea', album_img: '/assets/img-beats/aurea.png', 
    audio: '/assets/beats/aurea.mp3', genres: ['asian rock', 'pluggnb', 'chill'],
    dataLnc: '2023/09/18',
  },
  { id: '25', name: '4ever Alive', album_img: '/assets/img-beats/4everalive.png', 
    audio: '/assets/beats/4everalive.mp3', genres: ['chill', 'ambient'],
    dataLnc: '2023/09/19',
  },
  { id: '26', name: 'Hysteric', album_img: '/assets/img-beats/hysteric.png', 
    audio: '/assets/beats/hysteric.mp3', genres: ['plugg', 'pluggnb'],
    dataLnc: '2023/09/20',
  },
  { id: '27', name: 'Space', album_img: '/assets/img-beats/space.png', 
    audio: '/assets/beats/space.mp3', genres: ['rage', 'ambient'],
    dataLnc: '2023/09/21',
  },
  { id: '28', name: 'Fashion', album_img: '/assets/img-beats/Fashion.png', 
    audio: '/assets/beats/fashion.mp3', genres: ['rage', 'opium'],
    dataLnc: '2023/09/21',
  },
  { id: '29', name: 'Perk', album_img: '/assets/img-beats/perk.png', 
    audio: '/assets/beats/perk.mp3', genres: ['rage'],
    dataLnc: '2023/09/22',
  },
  { id: '30', name: 'Midnight', album_img: '/assets/img-beats/midnight.png', 
    audio: '/assets/beats/midnight.mp3', genres: ['westcoast'],
    dataLnc: '2023/09/26',
  },
  { id: '31', name: 'War', album_img: '/assets/img-beats/war.png', 
    audio: '/assets/beats/war.mp3', genres: ['gangsta'],
    dataLnc: '2023/09/27',
  },
  { id: '32', name: 'Bandolero', album_img: '/assets/img-beats/bandolero.png', 
    audio: '/assets/beats/bandolero.mp3', genres: ['detroit', 'gangsta'],
    dataLnc: '2023/10/01',
  },
  { id: '33', name: 'Prada walkin', album_img: '/assets/img-beats/pradawalkin.png', 
    audio: '/assets/beats/pradawalkin.mp3', genres: ['detroit', 'gangsta'],
    dataLnc: '2023/10/01',
  },
  { id: '34', name: 'Switch', album_img: '/assets/img-beats/switch.png', 
    audio: '/assets/beats/switch.mp3', genres: ['ambient', 'dark', 'spacial'],
    dataLnc: '2023/10/02',
  },{ id: '35', name: 'Emotions', album_img: '/assets/img-beats/emotions.png', 
  audio: '/assets/beats/emotions.mp3', genres: ['vibe', 'chill', 'emotional'],
  dataLnc: '2023/10/04',
},
{ id: '36', name: 'Horror', album_img: '/assets/img-beats/horror.png', 
  audio: '/assets/beats/horror.mp3', genres: ['dark', 'darkplugg', 'plugg'],
  dataLnc: '2023/10/05',
},
{ id: '37', name: 'Sky High', album_img: '/assets/img-beats/skyhigh.png', 
  audio: '/assets/beats/skyhigh.mp3', genres: ['plugg', 'pluggnb'],
  dataLnc: '2023/10/06',
},
{ id: '38', name: 'BootUp', album_img: '/assets/img-beats/bootup.png', 
  audio: '/assets/beats/bootup.mp3', genres: ['rage', 'agressive'],
  dataLnc: '2023/10/07',
},
{ id: '39', name: 'Servin', album_img: '/assets/img-beats/servin.png', 
  audio: '/assets/beats/servin.mp3', genres: ['glo', 'agressive', 'gangsta'],
  dataLnc: '2023/10/08',
},
{ id: '40', name: 'My luv', album_img: '/assets/img-beats/myluv.png', 
  audio: '/assets/beats/myluv.mp3', genres: ['pluggnb', 'plugg'],
  dataLnc: '2023/10/09',
},
{ id: '41', name: 'Beamer', album_img: '/assets/img-beats/beamer.png', 
  audio: '/assets/beats/beamer.mp3', genres: ['westcoast', 'gangsta'],
  dataLnc: '2023/10/11',
},
{ id: '42', name: 'Rain', album_img: '/assets/img-beats/rain.png', 
  audio: '/assets/beats/rain.mp3', genres: ['ambient', 'emotional'],
  dataLnc: '2023/10/15',
},
];

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === 'GET') {
    res.status(200).json(beats);
  } else {
    res.status(405).end();
  }
}