import type { NextApiRequest, NextApiResponse } from 'next'


export const beats = [
  { id: '1', name: 'Purple', album_img: '/assets/img-beats/purple.png', 
    audio: '/assets/beats/(pluggnb)purple_.mp3', genres: ['plugg', 'pluggnb'],
    dataLnc: '2023/01/24',
  },
  { id: '2', name: 'Slay', album_img: '/assets/img-beats/slay.png', 
    audio: '/assets/beats/slay.mp3', genres: ['dark', 'hard'],
    dataLnc: '2023/03/19',
  },
  { id: '3', name: 'Bape', album_img: '/assets/img-beats/bape.png', 
    audio: '/assets/beats/bape.mp3', genres: ['plugg', 'pluggnb'],
    dataLnc: '2023/04/03',
  },
  { id: '4', name: 'Angels', album_img: '/assets/img-beats/angels.png', 
    audio: '/assets/beats/angels.mp3', genres: ['ambient', 'dark', 'melodic', 'sad'],
    dataLnc: '2023/06/28',
  },
  { id: '5', name: 'Xanax Dreams', album_img: '/assets/img-beats/xanaxdreams.jpg', 
    audio: '/assets/beats/XanaxDreams.mp3', genres: ['ambient', 'chill'],
    dataLnc: '2023/07/26',
  },
  { id: '10', name: 'Cristals', album_img: '/assets/img-beats/cristalsbg.jpg', 
    audio: '/assets/beats/cristals.mp3', genres: ['ambient', 'chill'],
    dataLnc: '2023/07/30',
  },
  { id: '15', name: 'Better days', album_img: '/assets/img-beats/betterdays.png', 
    audio: '/assets/beats/betterdays.mp3', genres: ['westcoast', 'chill', 'gangsta'],
    dataLnc: '2023/08/09',
  },
  { id: '16', name: 'Clouds', album_img: '/assets/img-beats/clouds.png', 
    audio: '/assets/beats/clouds.mp3', genres: ['chill', 'lofi'],
    dataLnc: '2023/08/18',
  },
  { id: '17', name: 'Sea', album_img: '/assets/img-beats/sea.png', 
    audio: '/assets/beats/sea.mp3', genres: ['chill', 'lofi'],
    dataLnc: '2023/08/18',
  },
  { id: '18', name: 'Blank', album_img: '/assets/img-beats/blank.jpg', 
    audio: '/assets/beats/blank.mp3', genres: ['chill', 'dark', 'gangsta'],
    dataLnc: '2023/08/20',
  },
  { id: '19', name: 'Winter', album_img: '/assets/img-beats/winter.png', 
    audio: '/assets/beats/winter.mp3', genres: ['chill', 'altrock', 'vibe'],
    dataLnc: '2023/08/29',
  },
  { id: '20', name: 'Citric', album_img: '/assets/img-beats/citric.png', 
    audio: '/assets/beats/citric.mp3', genres: ['ambient', 'dark', 'chill', 'vibe'],
    dataLnc: '2023/08/31',
  },
  { id: '23', name: 'Diamonds', album_img: '/assets/img-beats/diamonds.png', 
    audio: '/assets/beats/diamonds.mp3', genres: ['gangsta', 'hard'],
    dataLnc: '2023/09/09',
  },
  { id: '24', name: 'Aurea', album_img: '/assets/img-beats/aurea.png', 
    audio: '/assets/beats/aurea.mp3', genres: ['asianrock', 'pluggnb', 'chill'],
    dataLnc: '2023/09/18',
  },
  { id: '30', name: 'Midnight', album_img: '/assets/img-beats/midnight.png', 
    audio: '/assets/beats/midnight.mp3', genres: ['westcoast'],
    dataLnc: '2023/09/26',
  },
  { id: '32', name: 'Bandolero', album_img: '/assets/img-beats/bandolero.png', 
    audio: '/assets/beats/bandolero.mp3', genres: ['detroit', 'gangsta'],
    dataLnc: '2023/10/01',
  },
  { id: '33', name: 'Prada walkin', album_img: '/assets/img-beats/pradawalkin.png', 
    audio: '/assets/beats/pradawalkin.mp3', genres: ['detroit', 'gangsta'],
    dataLnc: '2023/10/01',
  },
  { id: '34', name: 'Switch', album_img: '/assets/img-beats/switch.png', 
    audio: '/assets/beats/switch.mp3', genres: ['ambient', 'dark', 'spacial'],
    dataLnc: '2023/10/02',
  },{ id: '35', name: 'Emotions', album_img: '/assets/img-beats/emotions.png', 
  audio: '/assets/beats/emotions.mp3', genres: ['vibe', 'chill', 'emotional'],
  dataLnc: '2023/10/04',
},
{ id: '36', name: 'Horror', album_img: '/assets/img-beats/horror.png', 
  audio: '/assets/beats/horror.mp3', genres: ['dark', 'darkplugg', 'plugg'],
  dataLnc: '2023/10/05',
},
{ id: '37', name: 'Sky High', album_img: '/assets/img-beats/skyhigh.png', 
  audio: '/assets/beats/skyhigh.mp3', genres: ['plugg', 'pluggnb'],
  dataLnc: '2023/10/06',
},

{ id: '39', name: 'Servin', album_img: '/assets/img-beats/servin.png', 
  audio: '/assets/beats/servin.mp3', genres: ['glo', 'agressive', 'gangsta'],
  dataLnc: '2023/10/08',
},
{ id: '41', name: 'Beamer', album_img: '/assets/img-beats/beamer.png', 
  audio: '/assets/beats/beamer.mp3', genres: ['westcoast', 'gangsta'],
  dataLnc: '2023/10/11',
},
{ id: '42', name: 'Rain', album_img: '/assets/img-beats/rain.png', 
  audio: '/assets/beats/rain.mp3', genres: ['ambient', 'emotional'],
  dataLnc: '2023/10/15',
},
  { id: '45', name: 'Your calls', album_img: '/assets/img-beats/yourcalls.png', 
    audio: '/assets/beats/yourcalls.mp3', genres: ['detroit', 'gangsta', 'chill'],
    dataLnc: '2023/10/18',
  },
  { id: '46', name: 'Motivation', album_img: '/assets/img-beats/motivation.png', 
    audio: '/assets/beats/motivation.mp3', genres: ['detroit', 'gangsta', 'chill'],
    dataLnc: '2023/10/19',
  },
  { id: '48', name: 'Beethoven', album_img: '/assets/img-beats/bethoven.png', 
    audio: '/assets/beats/bethoven.mp3', genres: ['detroit', 'flint', 'gangsta'],
    dataLnc: '2023/10/21',
  },
  { id: '49', name: 'Heaven sent', album_img: '/assets/img-beats/heavensent.png', 
    audio: '/assets/beats/heavensent.mp3', genres: ['regalia'],
    dataLnc: '2023/10/22',
  },
  { id: '50', name: 'Universal', album_img: '/assets/img-beats/universal.jpg', 
    audio: '/assets/beats/universal.mp3', genres: ['regalia', 'motivational'],
    dataLnc: '2023/10/23',
  },
  { id: '51', name: 'Flawless', album_img: '/assets/img-beats/flawless.png', 
    audio: '/assets/beats/flawless.mp3', genres: ['glo', 'regalia', 'motivational'],
    dataLnc: '2023/10/24',
  },
  { id: '52', name: 'Crumble', album_img: '/assets/img-beats/crumble.png', 
    audio: '/assets/beats/crumble.mp3', genres: ['regalia', 'motivational'],
    dataLnc: '2023/10/30',
  },
  { id: '53', name: 'Toxic', album_img: '/assets/img-beats/toxic.png', 
    audio: '/assets/beats/toxic.mp3', genres: ['dark', 'rage', 'aggressive'],
    dataLnc: '2023/10/31',
  },
  { id: '56', name: 'Ethereal', album_img: '/assets/img-beats/ethereal.png', 
    audio: '/assets/beats/ethereal.mp3', genres: ['eletronic'],
    dataLnc: '2023/11/03',
  },
  { id: '57', name: 'Gone', album_img: '/assets/img-beats/gone.png', 
    audio: '/assets/beats/gone.mp3', genres: ['dark', 'rage', 'aggressive', 'gangsta'],
    dataLnc: '2023/11/04',
  },
  { id: '63', name: 'Flex like this', album_img: '/assets/img-beats/flexlikethis.png', 
    audio: '/assets/beats/flexlikethis.mp3', genres: ['vibe', 'hyperpop'],
    dataLnc: '2023/11/10',
  },
  { id: '64', name: 'Wind', album_img: '/assets/img-beats/wind.png', 
  audio: '/assets/beats/wind.mp3', genres: ['plugg', 'pluggnb', 'asianrock'],
  dataLnc: '2023/11/11',
},
{ id: '65', name: 'Lua', album_img: '/assets/img-beats/lua.png', 
  audio: '/assets/beats/lua.mp3', genres: ['pluggnb', 'plugg', 'emotional'],
  dataLnc: '2023/11/12',
},
{ id: '66', name: 'Honey', album_img: '/assets/img-beats/honey.png', 
  audio: '/assets/beats/honey.mp3', genres: ['pluggnb', 'chill'],
  dataLnc: '2023/11/13',
},
{ id: '67', name: 'Mirrors', album_img: '/assets/img-beats/mirrors.png', 
  audio: '/assets/beats/mirrors.mp3', genres: ['ambient', 'deep', 'dark'],
  dataLnc: '2023/11/14',
},
{ id: '68', name: 'Icon', album_img: '/assets/img-beats/icon.png', 
  audio: '/assets/beats/icon.mp3', genres: ['dark', 'opium'],
  dataLnc: '2023/11/15',
},
{ id: '69', name: 'Merciless', album_img: '/assets/img-beats/merciless.png', 
  audio: '/assets/beats/merciless.mp3', genres: ['dark', 'agressive', 'gangsta'],
  dataLnc: '2023/11/16',
},
{ id: '70', name: 'Power', album_img: '/assets/img-beats/power.png', 
  audio: '/assets/beats/power.mp3', genres: ['gangsta'],
  dataLnc: '2023/11/17',
},
{ id: '71', name: 'Sacred', album_img: '/assets/img-beats/sacred.png', 
  audio: '/assets/beats/sacred.mp3', genres: ['dark', 'agressive', 'opium'],
  dataLnc: '2023/11/18',
},
{ id: '72', name: 'Sides', album_img: '/assets/img-beats/sides.png', 
  audio: '/assets/beats/sides.mp3', genres: ['pluggnb', 'asianrock'],
  dataLnc: '2023/11/19',
},
{ id: '73', name: 'Float', album_img: '/assets/img-beats/float.png', 
  audio: '/assets/beats/float.mp3', genres: ['plugg', 'chill', 'pluggnb'],
  dataLnc: '2023/11/20',
},
{ id: '74', name: 'Maybach', album_img: '/assets/img-beats/maybach.png', 
  audio: '/assets/beats/maybach.mp3', genres: ['gangsta', 'dark', 'agressive'],
  dataLnc: '2023/11/21',
},
{ id: '75', name: 'Secrets', album_img: '/assets/img-beats/secrets.png', 
  audio: '/assets/beats/secrets.mp3', genres: ['ambient', 'dark', 'deep'],
  dataLnc: '2023/11/22',
},
{ id: '76', name: 'Cosmic', album_img: '/assets/img-beats/cosmic.png', 
  audio: '/assets/beats/cosmic.mp3', genres: ['ambient', 'chill', 'emotional'],
  dataLnc: '2023/11/23',
},
{ id: '77', name: 'Blow em', album_img: '/assets/img-beats/blowem.png', 
  audio: '/assets/beats/blowem.mp3', genres: ['rage'],
  dataLnc: '2023/11/24',
},
{ id: '78', name: 'Spaced out', album_img: '/assets/img-beats/spacedout.png', 
  audio: '/assets/beats/spacedout.mp3', genres: ['ambient', 'opium', 'spacial'],
  dataLnc: '2023/11/25',
},
{ id: '79', name: 'Attraction', album_img: '/assets/img-beats/attraction.png', 
  audio: '/assets/beats/attraction.mp3', genres: ['ambient', 'deep', 'dark'],
  dataLnc: '2023/11/26',
},
{ id: '80', name: 'Whip', album_img: '/assets/img-beats/whip.png', 
  audio: '/assets/beats/whip.mp3', genres: ['ambient', 'chill'],
  dataLnc: '2023/11/27',
},
{ id: '81', name: 'Plans', album_img: '/assets/img-beats/plans.png', 
  audio: '/assets/beats/plans.mp3', genres: ['motivational'],
  dataLnc: '2023/11/28',
},
{ id: '82', name: 'Ascendent', album_img: '/assets/img-beats/ascendent.png', 
  audio: '/assets/beats/ascendent.mp3', genres: ['regalia', 'motivational'],
  dataLnc: '2023/11/29',
},
{ id: '83', name: 'Goals', album_img: '/assets/img-beats/goals.png', 
  audio: '/assets/beats/goals.mp3', genres: ['regalia', 'motivational', 'dark'],
  dataLnc: '2023/11/30',
},
{ id: '84', name: 'Chinatown', album_img: '/assets/img-beats/chinatown.png', 
  audio: '/assets/beats/chinatown.mp3', genres: ['eletronic', 'dark'],
  dataLnc: '2023/12/01',
},
{ id: '85', name: 'Killer', album_img: '/assets/img-beats/killer.png', 
  audio: '/assets/beats/killer.mp3', genres: ['jerk', 'dark', 'agressive'],
  dataLnc: '2023/12/02',
},
{ id: '86', name: 'Advance', album_img: '/assets/img-beats/advance.png', 
  audio: '/assets/beats/advance.mp3', genres: ['rage', 'supertrap'],
  dataLnc: '2023/12/03',
},
{ id: '87', name: 'Spiral', album_img: '/assets/img-beats/spiral.png', 
  audio: '/assets/beats/spiral.mp3', genres: ['supertrap', 'rage'],
  dataLnc: '2023/12/04',
},
{ id: '88', name: 'Coldest', album_img: '/assets/img-beats/coldest.png', 
  audio: '/assets/beats/coldest.mp3', genres: ['newjazz', 'chill', 'motivational'],
  dataLnc: '2023/12/05',
},
{ id: '89', name: 'Hills', album_img: '/assets/img-beats/hills.png', 
  audio: '/assets/beats/hills.mp3', genres: ['ambient', 'chill', 'deep', 'dark'],
  dataLnc: '2023/12/06',
},
{ id: '90', name: 'Wicked Luv', album_img: '/assets/img-beats/wickedluv.png', 
  audio: '/assets/beats/wickedluv.mp3', genres: ['pluggnb', 'chill', 'emotional'],
  dataLnc: '2023/12/07',
},
{ id: '91', name: 'Illusions', album_img: '/assets/img-beats/illusions.png', 
  audio: '/assets/beats/illusions.mp3', genres: ['pluggnb', 'deep', 'dark', 'emotional'],
  dataLnc: '2023/12/08',
},
{ id: '92', name: 'Sanity', album_img: '/assets/img-beats/sanity.png', 
  audio: '/assets/beats/sanity.mp3', genres: ['supertrap', 'dark', 'motivational', 'spacial'],
  dataLnc: '2023/12/09',
},
{ id: '93', name: 'Dimension', album_img: '/assets/img-beats/dimension.png', 
  audio: '/assets/beats/dimension.mp3', genres: ['supertrap', 'spacial', 'dark'],
  dataLnc: '2023/12/10',
},
{ id: '94', name: 'Danger', album_img: '/assets/img-beats/danger.png', 
  audio: '/assets/beats/danger.mp3', genres: ['supertrap', 'rage', 'agressive', 'dark'],
  dataLnc: '2023/12/11',
},
{ id: '95', name: 'Pouring', album_img: '/assets/img-beats/pouring.png', 
  audio: '/assets/beats/pouring.mp3', genres: ['plugg', 'chill', 'motivational', 'vibe'],
  dataLnc: '2023/12/12',
},
{ id: '96', name: 'When it Rains', album_img: '/assets/img-beats/whenitrains.png', 
  audio: '/assets/beats/whenitrains.mp3', genres: ['ambient', 'chill', 'deep', 'emotional'],
  dataLnc: '2023/12/13',
},
{ id: '97', name: 'Elevated', album_img: '/assets/img-beats/elevate.png', 
  audio: '/assets/beats/elevate.mp3', genres: ['rage', 'supertrap', 'agressive'],
  dataLnc: '2023/12/14',
},
{ id: '98', name: 'Sippin', album_img: '/assets/img-beats/sippin.png', 
  audio: '/assets/beats/spinnin.mp3', genres: ['supertrap', 'dark', 'spacial'],
  dataLnc: '2023/12/15',
},
{ id: '99', name: 'X2C', album_img: '/assets/img-beats/x2c.png', 
  audio: '/assets/beats/x2c.mp3', genres: ['supertrap', 'ambient', 'chill'],
  dataLnc: '2023/12/16',
},
{ id: '100', name: 'AMG GT73', album_img: '/assets/img-beats/amgcedes.png', 
  audio: '/assets/beats/amgcedes.mp3', genres: ['supertrap', 'ambient', 'spacial', 'chill'],
  dataLnc: '2023/12/17',
},
{ id: '101', name: 'Synergy X', album_img: '/assets/img-beats/synergyx.png', 
  audio: '/assets/beats/synergyx.mp3', genres: ['supertrap', 'ambient', 'spacial', 'chill'],
  dataLnc: '2024/02/14',
},
{ id: '102', name: 'Tryptamine', album_img: '/assets/img-beats/tryptamine.png', 
  audio: '/assets/beats/tryptamine(141).mp3', genres: ['eletronic', 'ambient', 'spacial', 'chill'],
  dataLnc: '2024/02/16',
},
{ id: '103', name: 'Muddy days', album_img: '/assets/img-beats/muddydays.jpg', 
  audio: '/assets/beats/muddydays.mp3', genres: ['pluggnb', 'plugg', 'chill'],
  dataLnc: '2024/02/18',
},
{ id: '104', name: 'Swervin', album_img: '/assets/img-beats/swervin.jpg', 
  audio: '/assets/beats/swervin.mp3', genres: ['ambient', 'dark'],
  dataLnc: '2024/02/20',
},
{ id: '105', name: 'Frailty', album_img: '/assets/img-beats/frailty.jpg', 
  audio: '/assets/beats/frailty.mp3', genres: ['pluggnb', 'plugg', 'chill', 'dark'],
  dataLnc: '2024/02/24',
},
{ id: '106', name: 'Nasa', album_img: '/assets/img-beats/nasa.jpg', 
  audio: '/assets/beats/nasa.mp3', genres: ['spacial', 'ambient', 'chill'],
  dataLnc: '2024/02/27',
},
{ id: '107', name: 'Pluto', album_img: '/assets/img-beats/pluto.jpg', 
  audio: '/assets/beats/pluto(154).mp3', genres: ['spacial', 'ambient', 'dark'],
  dataLnc: '2024/03/01',
},
{ id: '108', name: 'Flyest', album_img: '/assets/img-beats/flyest.jpg', 
  audio: '/assets/beats/flyest(138).mp3', genres: ['spacial', 'ambient', 'chill', 'motivational'],
  dataLnc: '2024/03/02',
},
{ id: '109', name: 'Purity', album_img: '/assets/img-beats/purity.jpg', 
  audio: '/assets/beats/purity(142).mp3', genres: ['ambient', 'chill', 'motivational'],
  dataLnc: '2024/03/03',
},
{ id: '110', name: 'Liquid', album_img: '/assets/img-beats/liquid.jpg', 
  audio: '/assets/beats/liquid.mp3', genres: ['ambient', 'chill',  'motivational'],
  dataLnc: '2024/03/15',
},
{ id: '111', name: 'Scored', album_img: '/assets/img-beats/scored.jpg', 
  audio: '/assets/beats/scored(170).mp3', genres: ['ambient', 'spacial', 'rage', 'supertrap', 'motivational'],
  dataLnc: '2024/03/16',
},
{ id: '112', name: 'Spaceship', album_img: '/assets/img-beats/spaceship.jpg', 
  audio: '/assets/beats/spaceship(147)Fminor.mp3', genres: ['ambient', 'spacial', 'rage', 'supertrap', 'motivational'],
  dataLnc: '2024/03/21',
},
{ id: '113', name: 'Cybercity', album_img: '/assets/img-beats/cybercity.jpg', 
  audio: '/assets/beats/cybercity(133).mp3', genres: ['ambient', 'spacial', 'rage', 'supertrap', 'motivational'],
  dataLnc: '2024/03/28',
},
{ id: '114', name: 'Vamply', album_img: '/assets/img-beats/roller.jpg', 
  audio: '/assets/beats/roller(160)Eminor.mp3', genres: ['ambient', 'dark'],
  dataLnc: '2024/03/27',
},
{ id: '115', name: 'Geeker', album_img: '/assets/img-beats/geeker.png', 
  audio: '/assets/beats/geeker(140).mp3', genres: ['ambient', 'dark'],
  dataLnc: '2024/03/26',
},
{ id: '116', name: 'GreenRoom', album_img: '/assets/img-beats/greenroom.jpg', 
  audio: '/assets/beats/greenroom(155).mp3', genres: ['plugg', 'dark', 'darkplugg'],
  dataLnc: '2024/04/04',
},
{ id: '117', name: 'Scammed', album_img: '/assets/img-beats/scammed.jpg', 
  audio: '/assets/beats/scammed(140).mp3', genres: ['ambient', 'supertrap'],
  dataLnc: '2024/04/03',
},
{ id: '118', name: 'Indica', album_img: '/assets/img-beats/indica.jpg', 
  audio: '/assets/beats/indica(140)Eminor.mp3', genres: ['pluggnb', 'plugg', 'motivational'],
  dataLnc: '2024/04/05',
},
{ id: '119', name: 'Lines', album_img: '/assets/img-beats/lines.jpg', 
  audio: '/assets/beats/princess(166).mp3', genres: ['pluggnb', 'emotional'],
  dataLnc: '2024/04/06',
},
{ id: '120', name: 'Antartica', album_img: '/assets/img-beats/antartica.jpg', 
  audio: '/assets/beats/antartica.mp3', genres: ['pluggnb', 'emotional'],
  dataLnc: '2024/04/07',
},
{ id: '121', name: 'After', album_img: '/assets/img-beats/after.jpg', 
  audio: '/assets/beats/(plugg)after(133).mp3', genres: ['plugg', 'pluggnb', 'motivational'],
  dataLnc: '2024/04/08',
},
{ id: '122', name: 'Comet', album_img: '/assets/img-beats/comet.jpg', 
  audio: '/assets/beats/comet(143).mp3', genres: ['spacial', 'supertrap', 'motivational'],
  dataLnc: '2024/04/09',
}, 
{ id: '123', name: 'Ufo', album_img: '/assets/img-beats/ufo.png', 
  audio: '/assets/beats/ufo(158).mp3', genres: ['spacial', 'supertrap', 'motivational'],
  dataLnc: '2024/04/10',
},
{ id: '124', name: 'Generation', album_img: '/assets/img-beats/generation.jpg', 
  audio: '/assets/beats/generation(158).mp3', genres: ['spacial', 'supertrap', 'motivational'],
  dataLnc: '2024/04/11',
},
{ id: '125', name: 'Witcher', album_img: '/assets/img-beats/witcher.jpg', 
  audio: '/assets/beats/witcher(154).mp3', genres: ['spacial', 'supertrap', 'agressive', 'motivational'],
  dataLnc: '2024/04/12',
},
{ id: '126', name: 'Gate', album_img: '/assets/img-beats/gate.jpg', 
  audio: '/assets/beats/gate(142).mp3', genres: ['ambient', 'agressive'],
  dataLnc: '2024/04/13',
},
{ id: '127', name: 'Orbit', album_img: '/assets/img-beats/orbit.jpg', 
  audio: '/assets/beats/(ambient)orbit(126).mp3', genres: ['ambient', 'sad', 'emotional', 'spacial'],
  dataLnc: '2024/04/14',
},
{ id: '128', name: 'Moon', album_img: '/assets/img-beats/moon.jpg', 
  audio: '/assets/beats/moon(149).mp3', genres: ['ambient', 'emotional', 'spacial'],
  dataLnc: '2024/04/25',
},
{ id: '129', name: 'Plasma', album_img: '/assets/img-beats/plasma.jpg', 
  audio: '/assets/beats/plasma(152).mp3', genres: ['ambient','agressive', 'spacial'],
  dataLnc: '2024/04/26',
},
{ id: '130', name: 'DarkSine', album_img: '/assets/img-beats/darksine.jpg', 
  audio: '/assets/beats/darksine(154).mp3', genres: ['agressive', 'spacial'],
  dataLnc: '2024/04/27',
},
{ id: '131', name: 'Scape', album_img: '/assets/img-beats/scape.png', 
  audio: '/assets/beats/scape(156).mp3', genres: ['agressive', 'spacial'],
  dataLnc: '2024/04/28',
},
{ id: '132', name: 'Veneta', album_img: '/assets/img-beats/veneta.jpg', 
  audio: '/assets/beats/venetta(151).mp3', genres: ['chill', 'vibe', 'altrock'],
  dataLnc: '2024/04/29',
},
{ id: '133', name: 'Heart', album_img: '/assets/img-beats/heart.jpg', 
  audio: '/assets/beats/heart(142).mp3', genres: ['pluggnb', 'emotional'],
  dataLnc: '2024/04/26',
},
{ id: '134', name: 'Opera', album_img: '/assets/img-beats/opera.jpg', 
  audio: '/assets/beats/spacyviolin(146).mp3', genres: ['ambient', 'inspirational', 'regalia', 'spacial'],
  dataLnc: '2024/04/30',
},
{ id: '135', name: 'Stargaze', album_img: '/assets/img-beats/stargaze.jpg', 
  audio: '/assets/beats/stargaze(150).mp3', genres: ['spacial', 'inspirational', 'ambient'],
  dataLnc: '2024/05/01',
},
{ id: '136', name: 'Devil', album_img: '/assets/img-beats/devil.jpg', 
  audio: '/assets/beats/cold killer(152).mp3', genres: ['agressive', 'dark'],
  dataLnc: '2024/04/28',
},
{ id: '137', name: 'Sine', album_img: '/assets/img-beats/sine.jpg', 
  audio: '/assets/beats/sine(141).mp3', genres: ['ambient', 'spacial', 'pluggnb', 'chill'],
  dataLnc: '2024/05/02',
},
{ id: '138', name: 'Interestelar', album_img: '/assets/img-beats/interestelarbeat.jpg', 
  audio: '/assets/beats/interestelarV1(147bpm).mp3', genres: ['ambient', 'spacial', 'emotional'],
  dataLnc: '2024/05/03',
},
{ id: '139', name: 'Deep', album_img: '/assets/img-beats/deeponit.jpg', 
  audio: '/assets/beats/deep on it.mp3', genres: ['ambient', 'spacial', 'pluggnb', 'emotional'],
  dataLnc: '2024/05/04',
},
{ id: '140', name: 'Alchemy', album_img: '/assets/img-beats/alchemy.jpg', 
  audio: '/assets/beats/alchemy(136).mp3', genres: ['ambient', 'spacial', 'chill'],
  dataLnc: '2024/05/05',
},
{ id: '141', name: 'Ancient', album_img: '/assets/img-beats/ancient.jpg', 
  audio: '/assets/beats/ancient(150).mp3', genres: ['ambient', 'spacial', 'pluggnb', 'chill'],
  dataLnc: '2024/05/06',
},
{ id: '142', name: 'Maze Runner', album_img: '/assets/img-beats/mazerunner.jpg', 
  audio: '/assets/beats/deicide - maze runner(142bpm).mp3', genres: ['ambient', 'spacial', 'inspirational'],
  dataLnc: '2024/05/01',
},
{ id: '143', name: 'Void', album_img: '/assets/img-beats/void.jpg', 
  audio: '/assets/beats/deicide - void(150bpm).mp3', genres: ['spacial', 'inspirational', 'agressive'],
  dataLnc: '2024/05/07',
},
{ id: '144', name: 'Comfort Zone', album_img: '/assets/img-beats/comfortzone.jpg', 
  audio: '/assets/beats/comfort zone(132bpm).mp3', genres: ['pluggnb', 'emotional'],
  dataLnc: '2024/05/08',
},
{ id: '145', name: 'Gazing at U', album_img: '/assets/img-beats/gazingatu.jpg', 
  audio: '/assets/beats/gazing at u.mp3', genres: ['pluggnb', 'plugg', 'chill'],
  dataLnc: '2024/05/09',
},
{ id: '146', name: 'Express', album_img: '/assets/img-beats/express.jpg', 
  audio: '/assets/beats/(pluggnb)express.mp3', genres: ['pluggnb', 'plugg', 'emotional', 'chill'],
  dataLnc: '2024/05/10',
},
{ id: '147', name: 'Activist', album_img: '/assets/img-beats/activist.jpg', 
  audio: '/assets/beats/activist.mp3', genres: ['rage', 'inspirational'],
  dataLnc: '2024/05/12',
},
{ id: '148', name: 'Spectra', album_img: '/assets/img-beats/spectra.jpg', 
  audio: '/assets/beats/spectra(145bpm).mp3', genres: ['rage', 'supertrap', 'agressive'],
  dataLnc: '2024/05/13',
},
{ id: '149', name: 'Venom', album_img: '/assets/img-beats/venom.jpg', 
  audio: '/assets/beats/venom.mp3', genres: ['rage', 'supertrap', 'agressive'],
  dataLnc: '2024/05/13',
},
{ id: '150', name: 'Supreme', album_img: '/assets/img-beats/supreme.jpg', 
  audio: '/assets/beats/saturday(140bpm).mp3', genres: ['newjazz', 'inspirational'],
  dataLnc: '2024/05/11',
},
{ id: '151', name: 'ArcteriX', album_img: '/assets/img-beats/arcterix.jpg', 
  audio: '/assets/beats/arcterix(140bpm).mp3', genres: ['rage', 'supertrap', 'agressive'],
  dataLnc: '2024/05/14',
},
{ id: '152', name: 'Evolutive', album_img: '/assets/img-beats/evolutive.jpg', 
  audio: '/assets/beats/evolutive.mp3', genres: ['supertrap', 'ambient'],
  dataLnc: '2024/05/15',
},
{ id: '153', name: 'Reign', album_img: '/assets/img-beats/reign.jpg', 
  audio: '/assets/beats/reign(154bpm)-ambient.mp3', genres: ['supertrap', 'ambient'],
  dataLnc: '2024/05/16',
},
{ id: '154', name: 'Peak', album_img: '/assets/img-beats/peak.jpg', 
  audio: '/assets/beats/(supertrap)peak(151bpm).mp3', genres: ['supertrap', 'ambient'],
  dataLnc: '2024/05/17',
},
{ id: '155', name: 'Crystaline', album_img: '/assets/img-beats/crystaline.jpg', 
  audio: '/assets/beats/cristaline(131bpm).mp3', genres: ['emotional', 'ambient', 'sad', 'pluggnb'],
  dataLnc: '2024/05/28',
},
{ id: '156', name: 'Traveller', album_img: '/assets/img-beats/traveller.jpg', 
  audio: '/assets/beats/(ambient)traveller(152bpm).mp3', genres: ['ambient'],
  dataLnc: '2024/06/01',
},
{ id: '157', name: 'Dream', album_img: '/assets/img-beats/dream.jpg', 
  audio: '/assets/beats/dream(155bpm).mp3', genres: ['emotional', 'ambient', 'romantic'],
  dataLnc: '2024/06/02',
},
{ id: '158', name: 'Citylights', album_img: '/assets/img-beats/citylights.jpg', 
  audio: '/assets/beats/deicide x touchthwsky - citylights(171bpm).mp3', genres: ['ambient'],
  dataLnc: '2024/06/02',
},
{ id: '159', name: 'Projection', album_img: '/assets/img-beats/projection.jpg', 
  audio: '/assets/beats/projection(160bpm).mp3', genres: ['ambient', 'supertrap'],
  dataLnc: '2024/06/03',
},
{ id: '160', name: 'Merge', album_img: '/assets/img-beats/merge.jpg', 
  audio: '/assets/beats/(new_wave)merge(160bpm).mp3', genres: ['eletronic', 'supertrap', 'ambient', 'dark'],
  dataLnc: '2024/06/04',
},
].sort((a, b) => parseInt(a.id) - parseInt(b.id));


export default function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === 'GET') {
    res.status(200).json(beats);
  } else {
    res.status(405).end();
  }
}